#!/usr/bin/osascript
#========================================================================================        
# Title         : dark-mode.sh
# Description   : Check if you macOS is in dark mode and set the right theme/background for Apple_Terminal
# Usage         : ~/macOs-config-files/_zsh/lib/dark-mode
# Version       : 0.1   
# Date          : 2021-04-06
# Author        : Yohan W. Dunon
# Company       : Design Your Web (DYW)
# zsh_version   : 5.8   
# License       : Apache License 2.0
#========================================================================================
# Copyright (c)  Design Your Web (DYW)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#========================================================================================

# Check if dark mode and select the appropriate theme
on backgroundcolor()
tell application "System Events"
	set mode to dark mode of appearance preferences
end tell

if mode then
	set theme to "Solarized Dark"
else
	set theme to "Solarized Light"
end if
return theme
end backgroundcolor

# Change the theme
set newTheme to backgroundcolor()

tell application "Terminal"
set current settings of tabs of windows to settings set newTheme # Theme name
end tell